#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/wait.h>
#include <regex.h>
// Feel free to change the data structures generated by AI.

#define MAX_SYSCALLS 1024
#define TOP_N 5

int is_path=0;

typedef struct {
    char name[64];
    double time;
} syscall_stat;

typedef struct {
    syscall_stat stats[MAX_SYSCALLS];
    int count;
    double total_time;
} syscall_stats;

int parse_strace_line(char *line, char *syscall_name, double *time) {
    // 解析一行strace输出
    regex_t regex;
    regmatch_t matches[3];

    const char *pattern = "^([a-zA-Z_][a-zA-Z0-9_]*)\\(.*<[0-9.]+)>$";

    if(regcomp(&regex,pattern,REG_EXTENDED)!=0){
        return 0;
    }

    int ret = regexec(&regex,line,3,matches,0);
    if(ret !=0){
        regfree(&regex);
        return 0;
    }

    int name_start = matches[1].rm_so;
    int name_end = matches[1].rm_eo;
    int name_len=name_end-name_start;

    strncpy(syscall_name,line+name_start,name_len);
    syscall_name[name_len]='\0';

    int time_start = matches[2].rm_so;
    int time_end = matches[2].rm_eo;
    int time_len=time_end-time_start;

    char time_str[64];
    strncpy(time_str,line+time_start,time_len);
    time_str[time_len]='\0';

    *time = atof(time_str);

    regfree(&regex);
    return 1;
}

void add_syscall(syscall_stats *stats, const char *name, double time) {
    // 把一次syscall累加到统计表
    stats->total_time+=time;

    for (int i = 0;i<stats->count;i++){
        if (strcmp(stats->stats[i].name,name)==0){
            stats->stats[i].time+=time;
            return ;
        }
    }
        if(stats->count < MAX_SYSCALLS){
            strncpy(stats->stats[stats->count].name,name,sizeof(stats->stats[stats->count].name)-1);
            stats->stats[stats->count].name[sizeof(stats->stats[stats->count].name)-1]='\0';
            stats->stats[stats->count].time=time;
            stats->count+=1;
        }
    
}

void print_top_syscalls(syscall_stats *stats, int n) {
    //找到前n个耗时最多的syscall
    if (stats->count == 0 || stats->total_time <=0){
        return ;
    }

    syscall_stat temp[MAX_SYSCALLS];

    for (int i=0;i<stats->count;i++){
        temp[i]=stats->stats[i];
    }

    for(int i=0;i<stats->count;i++){
        for(int j=i+1;j<stats->count;j++){
            if(temp[j].time>temp[i].time){
                syscall_stat t = temp[i];
                temp[i]=temp[j];
                temp[j]=t;
            }
        }
    }

    int limit = n;
    if(limit > stats->count){
        limit = stats->count;
    }

    for(int i=0;i<limit;i++){
        int ratio = (int)(temp[i].time * 100/stats->total_time);
        printf("%s (%d%%)\n", temp[i].name, ratio);
    }
    

}

char *resolve_command(const char *command){
    if(command[0]=='/'){
        return strdup(command);
    }
    char *path_env=getenv("PATH");
    if(path_env==NULL)return NULL;

    char *path = strdup(path_env);
    char *ptr = NULL;

    for(char *i=strtok_r(path,":",&ptr);i!=NULL;i=strtok_r(NULL,":",&ptr)){
        char result[1024];
        snprintf(result,sizeof(result),"%s/%s",i,command);
        if(access(result,X_OK)==0){
            free(path);
            return strdup(result);
        }
    }

    free(path);
    return NULL;
}

int main(int argc, char *argv[]) {

    if(argc<2){
        fprintf(stderr,"Usage: %s COMMAND [ARG]...\n",argv[0]);
        exit(1);
    }
    //define argments
    char *command=argv[1];
    char *path=resolve_command(command);

    if(path == NULL){
        fprintf(stderr,"Cannot find path!");
        exit(1);
    }

    extern char **environ;

    // create pipe
    int fd[2];
    if(pipe(fd)<0){
        perror("pipe");
        exit(1);
    }

    // create child 
    pid_t pid = fork();
    if(pid<0){
        perror("fork");
        exit(1);
    }
    
    if(pid == 0){//child
        close(fd[0]);
        if (dup2(fd[1], STDERR_FILENO) < 0) {
            perror("dup2");
            exit(1);
        }
        close(fd[1]);

        //strace
        char **exec_argv= malloc (sizeof(char *)* (argc +2));
        exec_argv[0]="strace";
        exec_argv[1]="-T";
        exec_argv[2]=path;

        for(int i=2;i<argc;i++){
            exec_argv[i+1]=argv[i];
        }
        exec_argv[argc+1]=NULL;

        execve("strace",          exec_argv, environ);
        execve("/bin/strace",     exec_argv, environ);
        execve("/usr/bin/strace", exec_argv, environ);

        perror("execve strace");
        exit(1);
        
    }else{ //parent
        close(fd[1]);

        char buf[1024];
        ssize_t n ;
        while((n=read(fd[0],buf,sizeof(buf)-1))>0){
            buf[n]='\0';
            printf("%s",buf);
        }

        close(fd[0]);
        waitpid(pid,NULL,0);
    }
   return 0;
}
