#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/wait.h>

// Feel free to change the data structures generated by AI.

#define MAX_SYSCALLS 1024
#define TOP_N 5

int is_path=0;

typedef struct {
    char name[64];
    double time;
} syscall_stat;

typedef struct {
    syscall_stat stats[MAX_SYSCALLS];
    int count;
    double total_time;
} syscall_stats;

int parse_strace_line(char *line, char *syscall_name, double *time) {
    // 解析一行strace输出
    return 1;
}

void add_syscall(syscall_stats *stats, const char *name, double time) {
    // 把一次syscall耗时累加到统计表
}

void print_top_syscalls(syscall_stats *stats, int n) {
    //找到前n个耗时最多的syscall
    
    //printf("%s (%d%%)\n", syscall_name, ratio);

}

char *resolve_command(const char *command){
    if(command[0]=='/'){
        return strdup(command);
    }
    char *path_env=getenv("PATH");
    if(path_env==NULL)return NULL;

    char *path = strdup(path_env);
    char *ptr = NULL;

    for(char *i=strtok_r(path,":",&ptr);i!=NULL;i=strtok_r(NULL,":",&ptr)){
        char result[1024];
        snprintf(result,sizeof(result),"%s/%s",i,command);
        if(access(result,X_OK)==0){
            free(path);
            return strdup(result);
        }
    }

    free(path);
    return NULL;
}

int main(int argc, char *argv[]) {

    if(argc<2){
        fprintf(stderr,"Usage: %s COMMAND [ARG]...\n",argv[0]);
        exit(1);
    }
    //define argments
    char *command=argv[1];
    char *path=resolve_command(command);

    if(path == NULL){
        fprintf(stderr,"Cannot find path!");
        exit(1);
    }

    extern char **environ;

    // create pipe
    int fd[2];
    if(pipe(fd)<0){
        perror("pipe");
        exit(1);
    }

    // create child 
    pid_t pid = fork();
    if(pid<0){
        perror("fork");
        exit(1);
    }
    
    if(pid == 0){//child
        close(fd[0]);
        if (dup2(fd[1], STDERR_FILENO) < 0) {
            perror("dup2");
            exit(1);
        }
        close(fd[1]);

        //strace
        char **exec_argv= malloc (sizeof(char *)* (argc +2));
        exec_argv[0]="strace";
        exec_argv[1]="-T";
        exec_argv[2]=path;

        for(int i=2;i<argc;i++){
            exec_argv[i+1]=argv[i];
        }
        exec_argv[argc+1]=NULL;

        execve("strace",          exec_argv, environ);
        execve("/bin/strace",     exec_argv, environ);
        execve("/usr/bin/strace", exec_argv, environ);

        perror("execve strace");
        exit(1);
        
    }else{ //parent
        close(fd[1]);

        char buf[1024];
        ssize_t n ;
        while((n=read(fd[0],buf,sizeof(buf)-1))>0){
            buf[n]='\0';
            printf("%s",buf);
        }

        close(fd[0]);
        waitpid(pid,NULL,0);
    }
   return 0;
}
