#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/wait.h>
#include <sys/select.h>
#include <sys/time.h>
#include <fcntl.h>

// Feel free to change the data structures generated by AI.

#define MAX_SYSCALLS 1024
#define TOP_N 5

typedef struct {
    char name[64];
    double time;
} syscall_stat;

typedef struct {
    syscall_stat stats[MAX_SYSCALLS];
    int count;
    double total_time;
} syscall_stats;

int parse_strace_line(char *line, char *syscall_name, double *time) {
    // 解析一行strace输出
    char *lparen = strchr(line, '(');
    if (lparen == NULL) {
        return 0;
    }

    int name_len = lparen - line;
    if (name_len <= 0 || name_len >= 64) {
        return 0;
    }

    strncpy(syscall_name, line, name_len);
    syscall_name[name_len] = '\0';

    if(!((syscall_name[0]>='a' && syscall_name[0]<='z')||syscall_name[0]=='_')){
        return 0;
    }

    for(int i=0;syscall_name[i]!='\0';i++){
        char c=syscall_name[i];
        if(!((c>='a'&&c<='z')||(c>='0'&&c<='9')||(c=='_'))){
            return 0;
        }
    }
    char *lt = strrchr(line, '<');
    char *gt = strrchr(line, '>');

    if(strstr(line,"=")==NULL){
        return 0;
    }

    if(gt[1]!='\0'&& gt[1]!='\n'){
        return 0;
    }
    if (lt == NULL || gt == NULL || lt >= gt) {
        return 0;
    }

    int time_len = gt - lt - 1;
    if (time_len <= 0 || time_len >= 63) {
        return 0;
    }

    char time_str[64];
    strncpy(time_str, lt + 1, time_len);
    time_str[time_len] = '\0';

    *time = atof(time_str);
    return 1;
}

void add_syscall(syscall_stats *stats, const char *name, double time) {
    // 把一次syscall累加到统计表
    stats->total_time+=time;

    for (int i = 0;i<stats->count;i++){
        if (strcmp(stats->stats[i].name,name)==0){
            stats->stats[i].time+=time;
            return ;
        }
    }
        if(stats->count < MAX_SYSCALLS){
            strncpy(stats->stats[stats->count].name,name,sizeof(stats->stats[stats->count].name)-1);
            stats->stats[stats->count].name[sizeof(stats->stats[stats->count].name)-1]='\0';
            stats->stats[stats->count].time=time;
            stats->count+=1;
        }
    
}

void print_top_syscalls(syscall_stats *stats, int n) {
    //找到前n个耗时最多的syscall
    if(stats->count >0 && stats->total_time>0){
        syscall_stat temp[MAX_SYSCALLS];

        for (int i=0;i<stats->count;i++){
            temp[i]=stats->stats[i];
        }

        for(int i=0;i<stats->count;i++){
            for(int j=i+1;j<stats->count;j++){
                if(temp[j].time>temp[i].time){
                    syscall_stat t = temp[i];
                    temp[i]=temp[j];
                    temp[j]=t;
                }
            }
        }

        int limit = n;
        if(limit > stats->count){
            limit = stats->count;
        }

        for(int i=0;i<limit;i++){
            int ratio = (int)(temp[i].time * 100/stats->total_time);
            printf("%s (%d%%)\n", temp[i].name, ratio);
        }
}
    // 80 '\0'
    for (int i=0;i<80;i++){
        putchar('\0');
    }
    fflush(stdout);
}

char *resolve_command(const char *command){
    if(strchr(command,'/')!=NULL){
        return strdup(command);
    }
    char *path_env=getenv("PATH");
    if(path_env==NULL)return NULL;
    char *path = strdup(path_env);
    char *ptr = NULL;

    for(char *i=strtok_r(path,":",&ptr);i!=NULL;i=strtok_r(NULL,":",&ptr)){
        char result[1024];
        snprintf(result,sizeof(result),"%s/%s",i,command);
        if(access(result,X_OK)==0){
            free(path);
            return strdup(result);
        }
    }

    free(path);
    return NULL;
}

int main(int argc, char *argv[]) {

    if(argc<2){
        fprintf(stderr,"Usage: %s COMMAND [ARG]...\n",argv[0]);
        exit(1);
    }
    //define argments
    char *command=argv[1];
    char *path=resolve_command(command);

    if(path == NULL){
        fprintf(stderr,"Cannot find path!");
        exit(1);
    }

    extern char **environ;

    // create pipe
    int fd[2];
    if(pipe(fd)<0){
        perror("pipe");
        exit(1);
    }

    // create child 
    pid_t pid = fork();
    if(pid<0){
        perror("fork");
        exit(1);
    }
    
    if(pid == 0){//child
        close(fd[0]);

        if (dup2(fd[1], STDERR_FILENO) < 0) {
            perror("dup2");
            exit(1);
        }
        close(fd[1]);

        int  nullfd=open("/dev/null",O_WRONLY);
        if(nullfd < 0){
            perror("open /dev/null");
            exit(1);
        }

        if(dup2(nullfd,STDOUT_FILENO)<0){
            perror("dup2 stdout");
            exit(1);
        }

        close(nullfd);
        //strace
        char **exec_argv= malloc (sizeof(char *)* (argc +2));
        exec_argv[0]="strace";
        exec_argv[1]="-T";
        exec_argv[2]=path;

        for(int i=2;i<argc;i++){
            exec_argv[i+1]=argv[i];
        }
        exec_argv[argc+1]=NULL;

        execve("strace",          exec_argv, environ);
        execve("/bin/strace",     exec_argv, environ);
        execve("/usr/bin/strace", exec_argv, environ);

        perror("execve strace");
        exit(1);
        
    }else{ //parent
        close(fd[1]);

        syscall_stats stats = {0};
        char buf[1024];
        char line[4096];
        int line_len=0;
        int done = 0;

        int dirty=0;
        while(!done){
            fd_set rfds;
            FD_ZERO(&rfds);
            FD_SET(fd[0],&rfds);

            struct timeval tv;
            tv.tv_sec=0;
            tv.tv_usec=100000;

            int ret = select(fd[0]+1,&rfds,NULL,NULL,&tv);

            if(ret <0){
                perror("select");
                break;
            }

            if(ret == 0){
                if(dirty){
                    print_top_syscalls(&stats,TOP_N);
                    dirty=0;
                }
                continue;
            }

            if(FD_ISSET(fd[0],&rfds)){
                ssize_t n=read(fd[0],buf,sizeof(buf));
                if(n<0){
                    perror("read");
                    break;
                }

                if(n==0){
                    done = 1;
                    break;
                }

                for (ssize_t i=0;i<n;i++){
                    if(line_len<(int)sizeof(line)-1){
                        line[line_len++]=buf[i];
                    }
    
                    if(buf[i]=='\n'){
                        line[line_len]='\0';
    
                        char syscall_name[64];
                        double time;
    
                        if(parse_strace_line(line,syscall_name,&time)){
                            add_syscall(&stats,syscall_name,time);
                            dirty=1;
                        }
    
                        line_len=0;
                    }
        
                }
            }
        }

        if (line_len > 0) {
            line[line_len] = '\0';
        
            char syscall_name[64];
            double time;
        
            if (parse_strace_line(line, syscall_name, &time)) {
                add_syscall(&stats, syscall_name, time);
                dirty = 1;
            }
        }
        
        if(dirty==1 || stats.count==0){
            print_top_syscalls(&stats,TOP_N);
        }

        close(fd[0]);
        waitpid(pid,NULL,0);
    }
   return 0;
}
